-- supabase/migrations/20250819192100_add_visit_details_and_subscriptions.sql

-- ============================================
-- 1. Create user subscriptions table
-- ============================================
CREATE TABLE IF NOT EXISTS public.user_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  subscription_type text CHECK (subscription_type IN ('free', 'premium', 'pro')) DEFAULT 'free',
  started_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  is_active boolean DEFAULT true,
  stripe_customer_id text,
  stripe_subscription_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  UNIQUE(user_id)
);

-- Enable RLS
ALTER TABLE public.user_subscriptions ENABLE ROW LEVEL SECURITY;

-- Policies for subscriptions
CREATE POLICY "Users can view their own subscription" 
  ON public.user_subscriptions
  FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Service role can manage subscriptions" 
  ON public.user_subscriptions
  FOR ALL 
  USING (auth.role() = 'service_role');

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_user_subscriptions_user_id ON public.user_subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_subscriptions_active ON public.user_subscriptions(is_active);

-- ============================================
-- 2. Function to get visit details with counts
-- ============================================
CREATE OR REPLACE FUNCTION public.get_visit_details(visit_id_param bigint)
RETURNS TABLE(
  id bigint,
  city text,
  country text,
  country_code text,
  start_date date,
  end_date date,
  user_count bigint,
  plan_count bigint
) 
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    v.id,
    v.city,
    v.country,
    v.country_code,
    v.start_date,
    v.end_date,
    (SELECT COUNT(DISTINCT user_id) 
     FROM public.visits 
     WHERE city = v.city 
     AND daterange(start_date, end_date, '[]') && daterange(v.start_date, v.end_date, '[]')
    ) as user_count,
    (SELECT COUNT(*) 
     FROM public.events 
     WHERE city = v.city 
     AND date::date BETWEEN v.start_date AND v.end_date
    ) as plan_count
  FROM public.visits v
  WHERE v.id = visit_id_param;
END;
$$;

-- ============================================
-- 3. Function to get users visiting same city
-- ============================================
CREATE OR REPLACE FUNCTION public.get_visit_users(
  visit_id_param bigint, 
  limit_param int DEFAULT NULL
)
RETURNS TABLE(
  user_id uuid,
  full_name text,
  avatar_url text,
  bio text,
  nationality_code text,
  is_verified boolean,
  visit_start date,
  visit_end date,
  overlap_days int
) 
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  target_visit RECORD;
BEGIN
  -- Get the target visit details
  SELECT * INTO target_visit FROM public.visits WHERE id = visit_id_param;
  
  RETURN QUERY
  SELECT 
    p.id as user_id,
    p.full_name,
    p.avatar_url,
    p.bio,
    p.nationality_code,
    COALESCE(p.onboarding_completed, false) as is_verified,
    v.start_date as visit_start,
    v.end_date as visit_end,
    EXTRACT(DAY FROM 
      LEAST(v.end_date, target_visit.end_date) - 
      GREATEST(v.start_date, target_visit.start_date)
    )::int + 1 as overlap_days
  FROM public.visits v
  JOIN public.profiles p ON v.user_id = p.id
  WHERE v.city = target_visit.city
    AND v.user_id != target_visit.user_id
    AND daterange(v.start_date, v.end_date, '[]') && daterange(target_visit.start_date, target_visit.end_date, '[]')
  ORDER BY overlap_days DESC, v.created_at DESC
  LIMIT limit_param;
END;
$$;

-- ============================================
-- 4. Function to get plans in city during visit
-- ============================================
CREATE OR REPLACE FUNCTION public.get_visit_plans(visit_id_param bigint)
RETURNS TABLE(
  event_id bigint,
  title text,
  description text,
  image_uri text,
  date timestamp with time zone,
  location_name text,
  cost numeric,
  attendee_count bigint,
  host_name text,
  host_avatar text
) 
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  target_visit RECORD;
BEGIN
  -- Get the target visit details
  SELECT * INTO target_visit FROM public.visits WHERE id = visit_id_param;
  
  RETURN QUERY
  SELECT 
    e.id as event_id,
    e.title,
    e.description,
    e.image_uri,
    e.date,
    e.location_name,
    e.cost,
    (SELECT COUNT(*) FROM public.attendance WHERE event_id = e.id) as attendee_count,
    p.full_name as host_name,
    p.avatar_url as host_avatar
  FROM public.events e
  LEFT JOIN public.profiles p ON e.user_id = p.id
  WHERE e.city = target_visit.city
    AND e.date BETWEEN target_visit.start_date::timestamp AND (target_visit.end_date + interval '1 day')::timestamp
  ORDER BY attendee_count DESC, e.created_at DESC;
END;
$$;

-- ============================================
-- 5. Grant permissions for RPC functions
-- ============================================
GRANT EXECUTE ON FUNCTION public.get_visit_details(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_visit_users(bigint, int) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_visit_plans(bigint) TO authenticated;

-- ============================================
-- 6. Add helpful indexes for performance
-- ============================================
CREATE INDEX IF NOT EXISTS idx_visits_city ON public.visits(city);
CREATE INDEX IF NOT EXISTS idx_visits_user_dates ON public.visits(user_id, start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_events_city_date ON public.events(city, date);
CREATE INDEX IF NOT EXISTS idx_attendance_event_user ON public.attendance(event_id, user_id);

-- ============================================
-- 7. Insert default free subscription for existing users
-- ============================================
INSERT INTO public.user_subscriptions (user_id, subscription_type, is_active)
SELECT id, 'free', true
FROM public.profiles
WHERE NOT EXISTS (
  SELECT 1 FROM public.user_subscriptions 
  WHERE user_subscriptions.user_id = profiles.id
)
ON CONFLICT (user_id) DO NOTHING;

-- ============================================
-- 8. Create trigger to auto-create subscription for new users
-- ============================================
CREATE OR REPLACE FUNCTION public.handle_new_user_subscription()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.user_subscriptions (user_id, subscription_type, is_active)
  VALUES (NEW.id, 'free', true)
  ON CONFLICT (user_id) DO NOTHING;
  RETURN NEW;
END;
$$;

-- Drop trigger if exists and recreate
DROP TRIGGER IF EXISTS on_profile_created_subscription ON public.profiles;
CREATE TRIGGER on_profile_created_subscription
  AFTER INSERT ON public.profiles
  FOR EACH ROW 
  EXECUTE FUNCTION public.handle_new_user_subscription();

-- ============================================
-- 9. Add comments for documentation
-- ============================================
COMMENT ON TABLE public.user_subscriptions IS 'Tracks user subscription status for premium features';
COMMENT ON FUNCTION public.get_visit_details IS 'Returns visit details with user and plan counts for a specific visit';
COMMENT ON FUNCTION public.get_visit_users IS 'Returns users visiting the same city with overlapping dates';
COMMENT ON FUNCTION public.get_visit_plans IS 'Returns events/plans happening in a city during visit dates';

-- ============================================
-- 10. Verify installation
-- ============================================
DO $$
BEGIN
  RAISE NOTICE 'Migration 20250819192100_add_visit_details_and_subscriptions completed successfully';
  RAISE NOTICE 'Created: user_subscriptions table';
  RAISE NOTICE 'Created: get_visit_details() function';
  RAISE NOTICE 'Created: get_visit_users() function';
  RAISE NOTICE 'Created: get_visit_plans() function';
  RAISE NOTICE 'All existing users have been assigned free subscriptions';
END $$;