-- Create the new 'visits' table to store user's upcoming visit intentions
CREATE TABLE public.visits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  city text NOT NULL,
  country text,
  country_code text,
  start_date date NOT NULL,
  end_date date NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable Row Level Security for the new 'visits' table
ALTER TABLE public.visits ENABLE ROW LEVEL SECURITY;

-- Policies for 'visits': Users can manage their own visits and view others'
CREATE POLICY "Users can view all visits" ON public.visits FOR SELECT USING (true);
CREATE POLICY "Users can insert their own visits" ON public.visits FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own visits" ON public.visits FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own visits" ON public.visits FOR DELETE USING (auth.uid() = user_id);


-- Create the new 'messages' table for the chat feature
CREATE TABLE public.messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id bigint NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  content text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable Row Level Security for the new 'messages' table
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Policies for 'messages': Only event attendees can read or write messages
CREATE POLICY "Allow read for event attendees" ON public.messages FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM attendance
    WHERE attendance.event_id = messages.event_id AND attendance.user_id = auth.uid()
  )
);
CREATE POLICY "Allow insert for event attendees" ON public.messages FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM attendance
    WHERE attendance.event_id = messages.event_id AND attendance.user_id = auth.uid()
  )
);


-- Add new columns to the existing 'profiles' table
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS bio text,
ADD COLUMN IF NOT EXISTS birth_date date,
ADD COLUMN IF NOT EXISTS languages jsonb; -- Store languages as a JSON array


-- Add new columns to the existing 'events' table
ALTER TABLE public.events
ADD COLUMN IF NOT EXISTS end_date timestamp with time zone,
ADD COLUMN IF NOT EXISTS location_name text,
ADD COLUMN IF NOT EXISTS interests jsonb,
ADD COLUMN IF NOT EXISTS cost numeric,
ADD COLUMN IF NOT EXISTS cost_currency text,
ADD COLUMN IF NOT EXISTS is_private boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS country text,
ADD COLUMN IF NOT EXISTS country_code text;

-- Rename 'location' column to 'city' for clarity
ALTER TABLE public.events RENAME COLUMN location TO city;
