-- app/supabase/migrations/20250814130008_activity_plan_enhancements.sql

-- Add venues/destinations support (many-to-many relationship)
CREATE TABLE public.event_venues (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id bigint NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  venue_name text NOT NULL,
  venue_address text,
  venue_city text,
  venue_country text,
  venue_country_code text,
  venue_lat double precision,
  venue_lng double precision,
  order_index integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now()
);

-- Add cost breakdown
CREATE TABLE public.event_costs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id bigint NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  item_name text NOT NULL,
  amount numeric,
  currency text DEFAULT 'USD',
  is_optional boolean DEFAULT false,
  link_url text,
  created_at timestamp with time zone DEFAULT now()
);

-- Add fields to events table
ALTER TABLE public.events
ADD COLUMN IF NOT EXISTS is_one_day boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS is_all_day boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS guidelines_accepted boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS guidelines_accepted_at timestamp with time zone;

-- Enable RLS
ALTER TABLE public.event_venues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_costs ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Public can view event venues" ON public.event_venues FOR SELECT USING (true);
CREATE POLICY "Event creator can manage venues" ON public.event_venues FOR ALL USING (
  EXISTS (SELECT 1 FROM events WHERE events.id = event_venues.event_id AND events.user_id = auth.uid())
);

CREATE POLICY "Public can view event costs" ON public.event_costs FOR SELECT USING (true);
CREATE POLICY "Event creator can manage costs" ON public.event_costs FOR ALL USING (
  EXISTS (SELECT 1 FROM events WHERE events.id = event_costs.event_id AND events.user_id = auth.uid())
);