-- supabase/migrations/20250820124900_messaging_system_schema.sql
-- =====================================================
-- COMPLETE MESSAGING SYSTEM DATABASE SCHEMA
-- =====================================================

-- 1. CONVERSATIONS TABLE (for both DMs and group chats)
-- =====================================================
CREATE TABLE public.conversations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type text CHECK (type IN ('dm', 'group')) NOT NULL,
  name text, -- For group chats (plan names)
  event_id bigint REFERENCES public.events(id) ON DELETE CASCADE, -- For group chats
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_message_at timestamp with time zone,
  last_message_preview text,
  avatar_url text -- For group chat images
);

-- 2. CONVERSATION PARTICIPANTS (who can see each conversation)
-- =====================================================
CREATE TABLE public.conversation_participants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint REFERENCES public.conversations(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  joined_at timestamp with time zone DEFAULT now(),
  last_read_at timestamp with time zone,
  is_muted boolean DEFAULT false,
  UNIQUE(conversation_id, user_id)
);

-- 3. ENHANCED MESSAGES TABLE (supports both DMs and group chats)
-- =====================================================
ALTER TABLE public.messages 
ADD COLUMN IF NOT EXISTS conversation_id bigint REFERENCES public.conversations(id) ON DELETE CASCADE,
ADD COLUMN IF NOT EXISTS reply_to_id bigint REFERENCES public.messages(id),
ADD COLUMN IF NOT EXISTS is_edited boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS edited_at timestamp with time zone,
ADD COLUMN IF NOT EXISTS is_deleted boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS deleted_at timestamp with time zone,
ADD COLUMN IF NOT EXISTS message_type text CHECK (message_type IN ('text', 'image', 'location', 'system')) DEFAULT 'text',
ADD COLUMN IF NOT EXISTS metadata jsonb; -- For images, locations, etc.

-- Create index for conversation-based queries
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON public.messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON public.messages(created_at DESC);

-- 4. FRIEND SYSTEM TABLES
-- =====================================================
CREATE TABLE public.friendships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  addressee_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  status text CHECK (status IN ('pending', 'accepted', 'declined', 'blocked')) NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  UNIQUE(requester_id, addressee_id)
);

-- Index for fast friendship lookups
CREATE INDEX IF NOT EXISTS idx_friendships_requester ON public.friendships(requester_id);
CREATE INDEX IF NOT EXISTS idx_friendships_addressee ON public.friendships(addressee_id);
CREATE INDEX IF NOT EXISTS idx_friendships_status ON public.friendships(status);

-- 5. USER PRIVACY SETTINGS
-- =====================================================
CREATE TABLE public.user_privacy_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE UNIQUE,
  message_privacy text CHECK (message_privacy IN ('everyone', 'friends_only', 'nobody')) DEFAULT 'everyone',
  profile_visibility text CHECK (profile_visibility IN ('public', 'friends_only', 'private')) DEFAULT 'public',
  show_online_status boolean DEFAULT true,
  show_read_receipts boolean DEFAULT true,
  allow_friend_requests boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- 6. MESSAGE READ RECEIPTS
-- =====================================================
CREATE TABLE public.message_read_receipts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id bigint REFERENCES public.messages(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  read_at timestamp with time zone DEFAULT now(),
  UNIQUE(message_id, user_id)
);

-- 7. TYPING INDICATORS
-- =====================================================
CREATE TABLE public.typing_indicators (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint REFERENCES public.conversations(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  started_at timestamp with time zone DEFAULT now(),
  UNIQUE(conversation_id, user_id)
);

-- 8. BLOCKED USERS
-- =====================================================
CREATE TABLE public.blocked_users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blocker_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  blocked_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT now(),
  reason text,
  UNIQUE(blocker_id, blocked_id)
);

-- =====================================================
-- ENABLE ROW LEVEL SECURITY
-- =====================================================
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.friendships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_privacy_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_read_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.typing_indicators ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blocked_users ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- ROW LEVEL SECURITY POLICIES
-- =====================================================

-- Conversations: Users can only see conversations they're part of
CREATE POLICY "Users can view their conversations" ON public.conversations
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM conversation_participants
      WHERE conversation_id = conversations.id 
      AND user_id = auth.uid()
    )
  );

-- Conversation Participants: Users can see participants of their conversations
CREATE POLICY "Users can view participants of their conversations" ON public.conversation_participants
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM conversation_participants cp2
      WHERE cp2.conversation_id = conversation_participants.conversation_id 
      AND cp2.user_id = auth.uid()
    )
  );

-- Messages: Enhanced policy for conversation-based access
DROP POLICY IF EXISTS "Allow read for event attendees" ON public.messages;
DROP POLICY IF EXISTS "Allow insert for event attendees" ON public.messages;

CREATE POLICY "Users can read messages in their conversations" ON public.messages
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM conversation_participants
      WHERE conversation_id = messages.conversation_id 
      AND user_id = auth.uid()
    )
  );

CREATE POLICY "Users can send messages to their conversations" ON public.messages
  FOR INSERT WITH CHECK (
    auth.uid() = user_id AND
    EXISTS (
      SELECT 1 FROM conversation_participants
      WHERE conversation_id = messages.conversation_id 
      AND user_id = auth.uid()
    )
  );

-- Friendships: Users can manage their friendships
CREATE POLICY "Users can view their friendships" ON public.friendships
  FOR SELECT USING (
    auth.uid() = requester_id OR auth.uid() = addressee_id
  );

CREATE POLICY "Users can send friend requests" ON public.friendships
  FOR INSERT WITH CHECK (auth.uid() = requester_id);

CREATE POLICY "Users can update their friendships" ON public.friendships
  FOR UPDATE USING (
    auth.uid() = requester_id OR auth.uid() = addressee_id
  );

-- Privacy Settings: Users control their own settings
CREATE POLICY "Users can view their privacy settings" ON public.user_privacy_settings
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update their privacy settings" ON public.user_privacy_settings
  FOR ALL USING (auth.uid() = user_id);

-- Message Read Receipts
CREATE POLICY "Users can view read receipts for their messages" ON public.message_read_receipts
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM messages m
      JOIN conversation_participants cp ON cp.conversation_id = m.conversation_id
      WHERE m.id = message_read_receipts.message_id 
      AND cp.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can mark messages as read" ON public.message_read_receipts
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Typing Indicators
CREATE POLICY "Users can see typing in their conversations" ON public.typing_indicators
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM conversation_participants
      WHERE conversation_id = typing_indicators.conversation_id 
      AND user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update their typing status" ON public.typing_indicators
  FOR ALL USING (auth.uid() = user_id);

-- Blocked Users
CREATE POLICY "Users can manage their blocked list" ON public.blocked_users
  FOR ALL USING (auth.uid() = blocker_id);

-- =====================================================
-- FUNCTIONS & TRIGGERS
-- =====================================================

-- Function to auto-create conversation when event is created
CREATE OR REPLACE FUNCTION create_event_conversation()
RETURNS trigger AS $$
BEGIN
  -- Create a group conversation for the event
  INSERT INTO conversations (type, name, event_id, avatar_url)
  VALUES ('group', NEW.title, NEW.id, NEW.image_uri);
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_event_created
  AFTER INSERT ON events
  FOR EACH ROW
  EXECUTE FUNCTION create_event_conversation();

-- Function to add user to conversation when they join an event
CREATE OR REPLACE FUNCTION add_user_to_event_conversation()
RETURNS trigger AS $$
DECLARE
  conv_id bigint;
BEGIN
  -- Find the conversation for this event
  SELECT id INTO conv_id FROM conversations WHERE event_id = NEW.event_id;
  
  -- Add user as participant
  IF conv_id IS NOT NULL THEN
    INSERT INTO conversation_participants (conversation_id, user_id)
    VALUES (conv_id, NEW.user_id)
    ON CONFLICT DO NOTHING;
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_attendance_created
  AFTER INSERT ON attendance
  FOR EACH ROW
  EXECUTE FUNCTION add_user_to_event_conversation();

-- Function to create/get DM conversation
CREATE OR REPLACE FUNCTION get_or_create_dm_conversation(
  user1_id uuid,
  user2_id uuid
)
RETURNS bigint AS $$
DECLARE
  conv_id bigint;
BEGIN
  -- Check if DM conversation already exists
  SELECT c.id INTO conv_id
  FROM conversations c
  WHERE c.type = 'dm'
  AND EXISTS (
    SELECT 1 FROM conversation_participants WHERE conversation_id = c.id AND user_id = user1_id
  )
  AND EXISTS (
    SELECT 1 FROM conversation_participants WHERE conversation_id = c.id AND user_id = user2_id
  );
  
  -- If not, create new DM conversation
  IF conv_id IS NULL THEN
    INSERT INTO conversations (type) VALUES ('dm') RETURNING id INTO conv_id;
    
    -- Add both participants
    INSERT INTO conversation_participants (conversation_id, user_id)
    VALUES (conv_id, user1_id), (conv_id, user2_id);
  END IF;
  
  RETURN conv_id;
END;
$$ LANGUAGE plpgsql;

-- Function to update conversation's last message
CREATE OR REPLACE FUNCTION update_conversation_last_message()
RETURNS trigger AS $$
BEGIN
  UPDATE conversations
  SET 
    last_message_at = NEW.created_at,
    last_message_preview = LEFT(NEW.content, 100),
    updated_at = now()
  WHERE id = NEW.conversation_id;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_message_sent
  AFTER INSERT ON messages
  FOR EACH ROW
  WHEN (NEW.is_deleted = false)
  EXECUTE FUNCTION update_conversation_last_message();

-- Function to check if users can message each other
CREATE OR REPLACE FUNCTION can_users_message(
  sender_id uuid,
  receiver_id uuid
)
RETURNS boolean AS $$
DECLARE
  privacy_setting text;
  are_friends boolean;
  is_blocked boolean;
BEGIN
  -- Check if blocked
  SELECT EXISTS (
    SELECT 1 FROM blocked_users 
    WHERE (blocker_id = receiver_id AND blocked_id = sender_id)
    OR (blocker_id = sender_id AND blocked_id = receiver_id)
  ) INTO is_blocked;
  
  IF is_blocked THEN
    RETURN false;
  END IF;
  
  -- Get receiver's privacy setting
  SELECT message_privacy INTO privacy_setting
  FROM user_privacy_settings
  WHERE user_id = receiver_id;
  
  -- Default to 'everyone' if no setting exists
  IF privacy_setting IS NULL THEN
    privacy_setting := 'everyone';
  END IF;
  
  IF privacy_setting = 'nobody' THEN
    RETURN false;
  ELSIF privacy_setting = 'everyone' THEN
    RETURN true;
  ELSE -- friends_only
    SELECT EXISTS (
      SELECT 1 FROM friendships
      WHERE status = 'accepted'
      AND ((requester_id = sender_id AND addressee_id = receiver_id)
      OR (requester_id = receiver_id AND addressee_id = sender_id))
    ) INTO are_friends;
    
    RETURN are_friends;
  END IF;
END;
$$ LANGUAGE plpgsql;

-- Function to get pending friend requests count
CREATE OR REPLACE FUNCTION get_pending_requests_count(user_id uuid)
RETURNS bigint AS $$
BEGIN
  RETURN (
    SELECT COUNT(*)
    FROM friendships
    WHERE addressee_id = user_id
    AND status = 'pending'
  );
END;
$$ LANGUAGE plpgsql;

-- Clean up old typing indicators (run periodically)
CREATE OR REPLACE FUNCTION cleanup_typing_indicators()
RETURNS void AS $$
BEGIN
  DELETE FROM typing_indicators
  WHERE started_at < now() - interval '30 seconds';
END;
$$ LANGUAGE plpgsql;