-- =====================================================
-- User & content reporting (Apple App Store Guideline 1.2 — UGC safety)
-- =====================================================
-- Lets any authenticated user file a report about another user, a message,
-- an event/group plan, or a conversation. Reports are write-only for users:
-- a user may insert a report (as themselves) and read back the reports they
-- filed; they cannot read, edit, or delete anyone else's. Moderation/review
-- happens out of band via the service role (Supabase dashboard / back office).
--
-- Pairs with the in-app Block feature (public.blocked_users, already present)
-- and the "report / block" UI added to profiles, DMs and group plans.

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid references public.profiles(id) on delete set null,
  reported_user_id uuid references public.profiles(id) on delete set null,
  target_type text not null check (target_type in ('user', 'message', 'event', 'conversation')),
  target_id text,
  reason text not null,
  details text,
  status text not null default 'open' check (status in ('open', 'reviewing', 'actioned', 'dismissed')),
  created_at timestamp with time zone not null default now()
);

comment on table public.reports is
  'User-submitted reports of objectionable users/content (Apple Guideline 1.2). Reviewed via service role; reporter/reported FKs are SET NULL on account deletion so moderation history survives.';

create index if not exists reports_reported_user_idx on public.reports (reported_user_id);
create index if not exists reports_status_idx on public.reports (status);
create index if not exists reports_created_at_idx on public.reports (created_at desc);

alter table public.reports enable row level security;

-- Authenticated users can file a report, but only as themselves.
drop policy if exists "Users can file reports" on public.reports;
create policy "Users can file reports" on public.reports
  for insert to authenticated
  with check (auth.uid() = reporter_id);

-- Reporters can read back the reports they filed (e.g. to show a "reported" state).
drop policy if exists "Users can view their own reports" on public.reports;
create policy "Users can view their own reports" on public.reports
  for select to authenticated
  using (auth.uid() = reporter_id);

-- No user-facing UPDATE/DELETE: review and resolution are service-role only.

-- Lock down role grants (matches the phase-1 anon lockdown convention).
revoke all on public.reports from anon;
grant select, insert on public.reports to authenticated;
