-- =====================================================
-- Lifecycle / account-"warming" infrastructure (skeleton)
-- =====================================================
-- Plumbing for one-shot lifecycle jobs that "warm" newly created accounts —
-- e.g. users who sign up on the marketing website before installing the app.
-- The actual warm-up campaigns are decided later; this migration only lays the
-- generic, extensible rails:
--
--   * public.lifecycle_events — an append-only ledger of "we ran job X for
--     user Y with outcome Z". Its UNIQUE(user_id, job_key) constraint is the
--     idempotency backbone: each job runs at most once per user, forever.
--
-- The runner that reads/writes this table is the edge function
-- supabase/functions/lifecycle-runner (service_role — bypasses RLS). See that
-- function's README for the job-registry contract and the scheduling snippet.
--
-- This file is intentionally minimal: table + RLS lockdown + a commented-out
-- pg_cron schedule. No campaign logic lives in SQL.

create table if not exists public.lifecycle_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  -- Stable identifier of the job that produced this row (matches a
  -- LifecycleJob.key in the edge function's registry), e.g.
  -- 'welcome_incomplete_onboarding'.
  job_key text not null,
  -- Outcome recorded by the runner. 'failed' is terminal by design: because
  -- the runner skips any user already present for a job_key, a failed row will
  -- NOT be retried automatically (at-most-once beats double-send for warm-up
  -- email). Operators can DELETE a failed row to force a retry.
  status text not null check (status in ('sent', 'skipped', 'failed')),
  -- Free-form context: error message on failure, reason on skip, etc.
  detail text,
  created_at timestamptz not null default now(),
  -- Idempotency backbone: at most one lifecycle_events row per (user, job).
  -- The runner also relies on the resulting unique violation (23505) as a
  -- concurrency double-guard when two runner ticks overlap.
  constraint lifecycle_events_user_job_key unique (user_id, job_key)
);

comment on table public.lifecycle_events is
  'Ledger of one-shot lifecycle/"warming" jobs run per user. UNIQUE(user_id, job_key) enforces at-most-once. Written only by the service_role (lifecycle-runner edge function); no user-facing access.';

-- Reporting/observability helpers (dashboards by job + recency).
create index if not exists lifecycle_events_job_key_idx on public.lifecycle_events (job_key);
create index if not exists lifecycle_events_created_at_idx on public.lifecycle_events (created_at desc);

-- ---------------------------------------------------------------------------
-- RLS: service-role only.
-- ---------------------------------------------------------------------------
-- Enable RLS and add NO policies. With RLS on and zero policies, PostgREST
-- (anon / authenticated roles) is default-denied for every operation. The
-- service_role key used by the lifecycle-runner edge function bypasses RLS
-- entirely, so it can read/write freely. We also revoke the baseline table
-- grants from anon/authenticated to match the phase-1 anon-lockdown convention
-- used elsewhere in these migrations (see 20260613100000_* and
-- 20260613120000_create_reports_table.sql).
alter table public.lifecycle_events enable row level security;

revoke all on public.lifecycle_events from anon;
revoke all on public.lifecycle_events from authenticated;

-- ---------------------------------------------------------------------------
-- Scheduling (COMMENTED OUT — enable manually when a real campaign ships).
-- ---------------------------------------------------------------------------
-- The runner is an edge function; a cron tick just POSTs to it. Postgres can
-- do that with pg_cron (cron.schedule) + pg_net (net.http_post).
--
-- NOTE: NEITHER extension is enabled in this project yet — the only extension
-- created by these migrations is "postgis" (see 20250705180737_remote_schema.sql).
-- Enabling pg_cron/pg_net is a project-level action (Supabase Dashboard ->
-- Database -> Extensions, or the statements below). Do it deliberately, not as
-- a side effect of this migration — hence the whole block is commented out.
--
-- Do NOT hardcode the LIFECYCLE_RUNNER_AUTH secret into a committed migration.
-- Store it in Vault and read it at call time, or paste it directly when you
-- run cron.schedule by hand in the SQL editor.
--
--   -- 1) One-time: enable the extensions.
--   create extension if not exists pg_cron  with schema extensions;
--   create extension if not exists pg_net   with schema extensions;
--
--   -- 2) Schedule the runner hourly (top of every hour).
--   select cron.schedule(
--     'lifecycle-runner-hourly',
--     '0 * * * *',
--     $$
--       select net.http_post(
--         url     := 'https://<project-ref>.supabase.co/functions/v1/lifecycle-runner',
--         headers := jsonb_build_object(
--           'Content-Type',  'application/json',
--           'Authorization', 'Bearer ' || '<LIFECYCLE_RUNNER_AUTH>'
--         ),
--         body    := '{}'::jsonb
--       );
--     $$
--   );
--
--   -- To stop it later:
--   -- select cron.unschedule('lifecycle-runner-hourly');
